clear all
close all
clc
%% Loading Dataset
[label, inst] = libsvmread('/home/scipolla/Dropbox/Edinburgh_WORK/Matlab/libsvm-master/heart_scale');
data = inst;
h = 2; % kernel bandwidth parameter
kfun = @(x,y) kernel_func(h, x,y); % define kernel function
K = kfun(data,data);
['Condition Number of K = ', num2str(condest(K))]

% Problem Dimension
n = size(inst,1);

reg=false;
if reg 
    K=K+1E-2*eye(n);
    ['Condition Number of K+reg*I = ', num2str(condest(K))]
end
% The folling number is also the number clusters
Blocks=5;

%% Plotting kernel Matrices
savefigures = true;
FigPlot= true;

if FigPlot
    %% Kernel Matrices Plot
    KS=K;
    [ax,fh]=subplotsCM(1,2,[],[],3,3,2.8,2.8,0.5,3);
    [X, Y] = meshgrid(1:n, 1:n);
    patch(ax(1), X, Y, KS, ...
           'Marker', 's', 'MarkerFaceColor', 'flat', 'MarkerSize', 15, ...
           'EdgeColor', 'none', 'FaceColor', 'none');
    set(ax(1), ... 
    'ylim',         [1 n]              , ...
    'xlim',         [1 n] , ...
    'Box' ,         'on'          , ...
    'YDir',         'reverse', ...
    'PlotBoxAspectRatio',[n+1 n+1 1]  , ...
    'TickDir'     , 'in'          , ...
    'TickLength'  , [.02 .02]     , ...
    'XMinorTick'  , 'off'         , ...
    'YMinorTick'  , 'off'         , ...
    'YGrid'       , 'on'          , ...
    'XGrid'       , 'off'         , ...
    'XColor'      , [.3 .3 .3]    , ...
    'YColor'      , [.3 .3 .3]    , ...
    'LineWidth'   , 1            , ...        
    'FontSize'    , 18);
    cmap = flipud(colormap('hot'));
    colormap(ax(1),cmap)
    title(ax(1),['Non Clustered Data, h = ', num2str(h)],'FontSize',30,...
        'fontweight','bold','interpreter', 'latex');
%% Clustering
    idx=kmeans(inst,Blocks);
    [C,I]=sort(idx);
    KSS=KS(I,I);
    [X, Y] = meshgrid(1:n, 1:n);
    patch(ax(2), X, Y, KSS, ...
           'Marker', 's', 'MarkerFaceColor', 'flat', 'MarkerSize', 15, ...
           'EdgeColor', 'none', 'FaceColor', 'none');
    set(ax(2), ... 
    'ylim',         [1 n]              , ...
    'xlim',         [1 n] , ...
    'Box' ,         'on'          , ...
    'YDir',         'reverse', ...
    'PlotBoxAspectRatio',[n+1 n+1 1]  , ...
    'TickDir'     , 'in'          , ...
    'TickLength'  , [.02 .02]     , ...
    'XMinorTick'  , 'off'         , ...
    'YMinorTick'  , 'off'         , ...
    'YGrid'       , 'on'          , ...
    'XGrid'       , 'off'         , ...
    'XColor'      , [.3 .3 .3]    , ...
    'YColor'      , [.3 .3 .3]    , ...
    'LineWidth'   , 1            , ...        
    'FontSize'    , 18);
    title(ax(2),['Clustered Data, h = ', num2str(h), ', Clusters = ', num2str(Blocks)],...
        'FontSize',30,'fontweight','bold','interpreter', 'latex');
    colormap(ax(2),cmap)
    cb = colorbar('location','Manual', 'position', [0.93 0.1 0.02 0.81]);
    cb.Limits=[0 1];
    cb.FontSize = 20;
    set(gcf,'color','w');
    
    if savefigures  
        keyboard
        filename = ['./clusterdKernelMatricesh_',num2str(h)];
        savefig(filename);
        set(gcf, 'PaperPositionMode', 'auto');
        print(filename,'-depsc2', '-r600'); 
    end
end

%% Block-Gauss-Seidel with Random-Permutations&Blocks vs Blocks from Clusters
seed=10;
rng(seed);

%GS Maxiter

Maxiter=50;

%Initial guess and RHS (we solve Kx=b)
x0    =  rand(n,1);
%xstar =  rand(n,1);
%b     =  K*xstar;
b     =  rand(n,1);

%Initial Residual
res0=norm(K*x0-b,2);
%
res_hist_rGS = zeros(Maxiter,1);

%Random Block-Gauss-Seidel
x=x0;
for iter=1:Maxiter
    Perm=randperm(n);
    %Perm=[1:n]';
    KPerm=K(Perm,Perm);
    KL=zeros(n,n);
    sizeBlocks=floor(n/Blocks);
    for j=1:Blocks
        if j ~= Blocks
        KL((j-1)*sizeBlocks+1:end,(j-1)*sizeBlocks+1:j*sizeBlocks)=...
            KPerm((j-1)*sizeBlocks+1:end,(j-1)*sizeBlocks+1:j*sizeBlocks);
        else
        KL((j-1)*sizeBlocks+1:end,(j-1)*sizeBlocks+1:end)=...
            KPerm((j-1)*sizeBlocks+1:end,(j-1)*sizeBlocks+1:end);
        end
    end 
    KU=KL-KPerm;
    x=KL\(KU*x(Perm)+b(Perm));
    invPerm=zeros(n,1);
    invPerm(Perm)=[1:n]';
    x=x(invPerm);
    res_hist_rGS(iter)=norm(K*x-b,2);
end

res_hist_bcGS= zeros(Maxiter,1);

%Gauss-Seidel Based on Clusters blocks
x=x0;
%Computing Sizes of Blocks

blocks_sizes=zeros(Blocks,1);

for j=1:Blocks
    blocks_sizes(j)=size(find(C==j),1);
end 
KL=zeros(n,n);

for j=1:Blocks
        if j==1
            start=0;
        else
            start=sum(blocks_sizes(1:j-1));
        end
        KL(start+1:end,start+1:sum(blocks_sizes(1:j)))=...
            KSS(start+1:end,start+1:sum(blocks_sizes(1:j)));
end
KU=KL-KSS;
invPerm=zeros(n,1);
invPerm(I)=[1:n]';

for iter=1:Maxiter
    x=KL\(KU*x(I)+b(I));
    x=x(invPerm);
    res_hist_bcGS(iter)=norm(K*x-b,2);
end


if FigPlot
    %Residuals Plots
    [ax_r,fh_r]=subplotsCM(1,2,[],[],5,1,2.8,2.8,0.5,3);
    plot(ax_r(1),[0:Maxiter],[res0;res_hist_rGS]./res0,...
        '-','markersize',15,'linewidth',5)
    set(ax_r(1), ... 
    'ylim',         [min([res0;res_hist_rGS]./res0) max([res0;res_hist_rGS]./res0)]              , ...
    'xlim',         [0 Maxiter] , ...
    'Box'         , 'on'          , ...
    'PlotBoxAspectRatio',[1 1 1]  , ...
    'TickDir'     , 'in'          , ...
    'TickLength'  , [.02 .02]     , ...
    'XMinorTick'  , 'off'         , ...
    'YMinorTick'  , 'off'         , ...
    'YGrid'       , 'on'          , ...
    'XGrid'       , 'off'         , ...
    'XColor'      , [.3 .3 .3]    , ...
    'YColor'      , [.3 .3 .3]    , ...
    'Yscale'      , 'log'   , ...
    'LineWidth'   , 1            , ...        
    'FontSize'    , 22);        

    title(ax_r(1),['Randomly Shuffled Block-GS'],'FontSize',30,...
        'fontweight','bold','interpreter', 'latex');
    ylabel(ax_r(1),'$\|\mathbf{r}^k\|/\|\mathbf{r}^0\|$','FontSize',30,...
        'fontweight','bold','interpreter', 'latex');
    xlabel(ax_r(1),'Iterations','FontSize',30,...
        'fontweight','bold','interpreter', 'latex');
    
    %
    plot(ax_r(2),[0:Maxiter],[res0;res_hist_bcGS]./res0,...
        '-','markersize',15,'linewidth',5)
    set(ax_r(2), ... 
    'ylim',         [min([res0;res_hist_bcGS]./res0) max([res0;res_hist_bcGS]./res0)]              , ...
    'xlim',         [0 Maxiter] , ...
    'Box'         , 'on'          , ...
    'PlotBoxAspectRatio',[1 1 1]  , ...
    'TickDir'     , 'in'          , ...
    'TickLength'  , [.02 .02]     , ...
    'XMinorTick'  , 'off'         , ...
    'YMinorTick'  , 'off'         , ...
    'YGrid'       , 'on'          , ...
    'XGrid'       , 'off'         , ...
    'XColor'      , [.3 .3 .3]    , ...
    'YColor'      , [.3 .3 .3]    , ...
    'Yscale'      , 'log'   , ...
    'LineWidth'   , 1            , ...        
    'FontSize'    , 22);        

    title(ax_r(2),['Block-GS (blocks from clustering)'],'FontSize',30,...
        'fontweight','bold','interpreter', 'latex');
    ylabel(ax_r(2),'$\|\mathbf{r}^k\|/\|\mathbf{r}^0\|$','FontSize',30,...
        'fontweight','bold','interpreter', 'latex');
    xlabel(ax_r(2),'Iterations','FontSize',30,...
        'fontweight','bold','interpreter', 'latex');
    set(gcf,'color','w');

    if savefigures  
        keyboard
        filename = ['./Residualsh_',num2str(h)];
        savefig(filename);
        set(gcf, 'PaperPositionMode', 'auto');
        print(filename,'-depsc2', '-r600'); 
    end
end

